from enum import Enum

class CodigoOperacion(Enum):
    #Código para una accion exitosa en general
    EXITO_REPARACION = "EXITO_REPARACION"
    EXITO_REEMPLAZO = "EXITO_REEMPLAZO"
    EXITO_INSTALACION = "EXITO_INSTALACION"
    COMPONENTE_FUNCIONAL = "COMPONENTE_FUNCIONAL"

    #Código para los diferentes diagnosticos
    
    #RAM
    SLOT_OCUPADO  = "SLOT_OCUPADO"
    CAPACIDAD_MAXIMA_GB_EXCEDIDA = "CAPACIDAD_MAXIMA_GB_EXCEDIDA"
    
    #PANTALLA
    TAMANO_PANTALLA_INCORRECTA = "TAMANO_PANTALLA_INCORRECTA"
    PANTALLA_ROTA = "PANTALLA_ROTA"
    
    #BATERIA
    BATERIA_DESCONECTADA = "BATERIA_DESCONECTADA"
    BATERIA_CONECTADA = "BATERIA_CONECTADA"
    VOLTAJE_BATERIA_INCORRECTO = "VOLTAJE_BATERIA_INCORRECTO"
    FORMA_BATERIA_INCORRECTA = "FORMA_BATERIA_INCORRECTA"
    BATERIA_DEGRADADA = "BATERIA_DEGRADADA"

    #CPU
    CPU_INCOMPATIBLE = "CPU_INCOMPATIBLE"
    CPU_SOBRECALENTADO = "CPU_SOBRECALENTADO"
    GPU_FALLA = "GPU_FALLA"
    SSD_DANADO = "SSD_DANADO"

    #Código para remplazo / reparación

    NO_REEMPLAZABLE = "NO_REEMPLAZABLE"
    NO_REPARABLE = "NO_REPARABLE"
    INCOMPATIBLE = "INCOMPATIBLE"